server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todeal
    username: postgres
    password: 1326
    security:
      user:
        name: admin
        password: 1234


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

    redis:
      host: localhost
      port: 6379


logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql.BasicBinder: off

firebase:
  credentials:
    path: firebase-adminsdk.json

bootpay:
  rest-api-key: ${BOOTPAY_REST_API_KEY}
  private-key: ${BOOTPAY_PRIVATE_KEY}

